### ISSUE TITLE
Absolute Touch control is offset with most custom resolutions

### ISSUE THREAD

**Issue by Senjar** [xyzz/openmw-android#16] opened 2019-06-25 11:26 UTC
4:3 Custom resolutions work with absolute touch 
but most 16:9 resolutions (except 1920x1080) are offset.
Seems like the top left corner is fine but while you move to bottom right the touch is shifting further than the finger.
Haven't tested 18.5:9, 16:10 and other aspect ratios.

**Comment by bbbazooka75** [comment] 2019-07-17 01:17
Tested using 18.5:9 aspect ratio (Samsung Galaxy Note8).
Hybrid touch control appears to work correctly when app is first opened but when switching out of the app with the overview button and switching back, the touch control becomes offset. Switching back and forth to the app causes the offset to change either increasing or decreasing. On-screen buttons appear to not be affected.
![not-offset-cursor](https://user-images.githubusercontent.com/52983384/61339947-1feac980-a80e-11e9-9ebe-c7dc46629b2a.jpeg)
![offset-cursor](https://user-images.githubusercontent.com/52983384/61339948-1feac980-a80e-11e9-905d-cdfcca2e8405.jpeg)

------------------------------------------------------------
Device resolution: 2960 x 1440 px
Custom game resolution: 2220 x 1080 px
GUI scaling factor: 1.85
Mouse mode in menus: Hybrid
Graphics library: GLESv2

**Comment by xyzz** [comment] 2019-11-02 02:43
Not able to reproduce on Pixel 1 running Android 10. What Android version are you on?

Tested resolutions:
- 640x480
- 1280x720
- 960x540

Tested scenarios:
- switching from the app to app overview and back
- switching from the app to the launcher and back
- switching from the app to the launcher, rotating the phone, and switching back

**Comment by licaon-kter** [comment] 2019-11-02 07:57
Seeing this on Mate 9 Android 9, custom 1280x720 (default is 1920x1080)


Seeing this on Xiaomi K20/9T Pro, custom 1560x720 (default 2340x1080)

**Comment by xyzz** [comment] 2019-11-02 17:33
> Seeing this on Xiaomi K20/9T Pro, custom 1560x720 (default 2340x1080) with Absolute

Is this also Android 9?

**Comment by licaon-kter** [comment] 2019-11-02 18:09
No, MIUI11 w/ Android 10

**Comment by xyzz** [comment] 2020-03-29 18:28
Fixed in 714179608a4160dfc31568fa8e88165a49b16e48

**Closed by xyzz** 2020-03-29 18:28 UTC

**Comment by licaon-kter** [comment] 2020-03-30 00:37
Confirmed, thanks
