### ISSUE TITLE
Mods don't load anymore since 0.46.0-26-nightly

### ISSUE THREAD

**Issue by Keksus1** [xyzz/openmw-android#25] opened 2019-10-17 16:59 UTC
Both 0.46.0-26-nightly and 0.46.0-27-nightly stopped loading the mod files which I wrote into the openmw.cfg in main storage/omw_nightly_config.

**Comment by licaon-kter** [comment] 2019-10-17 17:08
Gist of your openmw.cfg? Works fine here...


App from F-Droid or Play store?

**Comment by WH1T3No1SE** [comment] 2019-10-20 22:10
Mods are loading for me on 0.46.0-27

**Comment by xyzz** [comment] 2019-11-02 02:26
My understanding is that it is a regression in OpenMW that only applies to a very specific setup with a custom openmw.cfg, possibly introduced by https://github.com/OpenMW/openmw/commit/1f3f3dd1a545740a907f9ad5e9165fda7f9e7a94

However,
- from OpenMW point of view, the android port isn't using configuration files correctly (data files are supposed to live in the user config, which is by design empty in the Android port)
- Android port has a mod manager, with the downside being that you have to put all of your mods into the same folder and potentially overwrite existing files. Therefore, if we were to spend the effort it is better to spend it improving the mod manager
- Even if the commit I've pointed out is the correct one, I'd rather not add a revert for this specific feature, as per the effort/benefit of maintaining it.

This will have to be a wontfix for now.

**Closed by xyzz** 2019-11-02 02:26 UTC
