### ISSUE TITLE
Camera bug since Android 11

### ISSUE THREAD

**Issue by JaegerSupreem** [xyzz/openmw-android#87] opened 2021-05-11 16:18 UTC
Whenever I touch the left digital stick first(movement) and then right stick(camera) camera goes wierd. Present in both joystick only and hybrid controls(Attached video).
-Using stable version 0.46.0-40
-Cannot use Nightly as it's not recognising the game in sd card as said in previous issue post.
-Using Samsung Galaxy M51 with Snapdragon 730g and 6GB ram.
https://youtu.be/iVzrKD5JxdM

**Comment by JaegerSupreem** [comment] 2021-05-12 13:13
> Duplicate of #63 ?

based on the explanation it seems so but the video shown in it is isn't the issue I mentioned as the issue I've mentioned makes camera stick move automatically as shown in my video

**Comment by JaegerSupreem** [comment] 2021-05-14 21:19
I tried the game on nightly build and this camera bug still persists in it.

**Comment by xyzz** [comment] 2021-05-14 21:21
it's duplicate of #63, the video posted in #63 might be of different bug however

**Closed by xyzz** 2021-05-14 21:21 UTC
