### ISSUE TITLE
the game crashes when the log file overflows with errors.

### ISSUE THREAD

**Issue by pulion** [xyzz/openmw-android#62] opened 2021-01-24 06:26 UTC
the game log file overflows with an error message, and after some time crashes:
[14:24:56.018 W] Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)
Version APK: 0.47-41
 - Device: Asus ROG phone 3 12/256
 - OS: Android 10
 - Version: ww_phone-17.0823.2012.122 
 - App source: Google Play store, F-Droid

**Comment by AbduSharif** [comment] 2021-01-25 00:57
That warning is unrelated, the crash happened because of something else.

I have that warning spammed with my builds but the game doesn't crash, that error is likely something bugged with GL4ES.

**Comment by docent27** [comment] 2021-02-02 15:02
Yes, there are mistakes! I've compiled many APKs on various commits and found that bugs started showing up after this commit:
https://github.com/OpenMW/openmw/commit/b22418d053a449905e2df7bb77a56827161a0c1b

I really don't understand how this is related to the OSG rendering error, but based on the results of the checks, it all started from here. I made an APK and sent it to a person who has this error (it doesn't exist on my device)

I apologize for my English, I am writing through a translator.

**Comment by pulion** [comment] 2021-02-05 07:48
when using shaders from Vtastek, these errors are absent in the log and the game does not crash.

**Comment by pulion** [comment] 2021-02-08 09:09
with the release of the new version of the APK, the errors did not disappear and the emulator became much worse.  now the processor is loaded only by 12-15%.  But the video is 100% loaded and the log file is covered with spam about a render error.
![Screenshot_20210208-110108527](https://user-images.githubusercontent.com/62562178/107198360-aae97100-69fd-11eb-8a8b-2f019055e1c9.jpg)
Log-file:
https://drive.google.com/file/d/19vX28TAyL3I3fcuOeRzGR415jdxmy8JB/view?usp=drivesdk


[openmw.log](https://github.com/xyzz/openmw-android/files/5942437/openmw.log)

**Comment by pulion** [comment] 2021-02-08 09:43
when i disable grass instancing and enable grass mods in mod manager then i get stable 30 fps.  but render errors are still present in the log file.
![Screenshot_20210208-113824804](https://user-images.githubusercontent.com/62562178/107202447-e2a6e780-6a02-11eb-8ad2-72034b89a9b1.jpg)

**Comment by akortunov** [comment] 2021-02-08 12:15
> found that bugs started showing up after this commit

This commit is irrelevant to rendering and partially reverted in upstream master. Attempts to revert the rest did not solve the issue, so probably you detected a wrong commit.

**Comment by xyzz** [comment] 2021-02-10 16:31
So apparently this only happens when you have MFR activated (which isn't mentioned anywhere in the issue).

**Comment by pulion** [comment] 2021-02-10 16:38
> So apparently this only happens when you have MFR activated (which isn't mentioned anywhere in the issue).

yes, sorry for not indicating, it really is.  the problem arises on the MFR and the assembly from Bransen.  this does not show up on the vanilla version of the game.  with MFR this was also not the case until version 0.47-040.  on version 0.47-39 everything is fine

**Comment by docent27** [comment] 2021-02-10 17:25
I want to share the results of my tests. I used your sources and built various versions of openmw and gl4es. This problem currently does not depend on the version of gles (on any version of the error in the logs, both on the most recent and on the oldest). The openmw developers did something between 11/29/2020 (40 nightly) and 01/03/2021 (41 nightly). https://github.com/OpenMW/openmw/commit/b22418d053a449905e2df7bb77a56827161a0c1b - errors start with this commit (although it does not affect rendering). Unfortunately, I couldn't roll back or make a patch for this commit to check the correctness. Yes, this problem exists with heavy mods such as MFR. If you play vanilla, these problems are not. And until recently, these problems were not even with this mod.

**Comment by xyzz** [comment] 2021-02-10 18:09
Most of these error messages are caused by osg using GL_POLYGON_OFFSET_LINE/GL_POLYGON_OFFSET_POINT mode which isn't supported on gles. It shouldn't affect anything, regardless I've patched it out just so that it doesn't spam the log. you can try the new build and let me know if it works any better.

**Comment by docent27** [comment] 2021-02-10 18:29
Thanks! I will now make an APK based on your patch, I'll take a look. If it helped, I will be very grateful to you!

**Comment by akortunov** [comment] 2021-02-10 18:52
It is not really a solution, it is just a temporary workaround. If gl4es does not support some functions which OpenMW uses, it would be better to ask gl4es devs to implement them rather that comment out random stuff. So far I do not see any related feature requests on the gl4es repo.

**Comment by docent27** [comment] 2021-02-10 18:57
Unfortunately GL4ES is not able to do a lot. Shadows, glare from the sun. If this patch solves our problem on android, that's already a success! I will make an APK in the very near future and AkaGloomy and I will check it, if the problem disappeared and it had a positive effect on FPS and crashes disappeared - we will be very happy with this solution!

**Comment by docent27** [comment] 2021-02-10 19:12
I thank you! Our problem is a thing of the past! Now the game works without problems! I have no more errors in the log! I'm happy!

**Comment by akortunov** [comment] 2021-02-10 19:32
> Unfortunately GL4ES is not able to do a lot. Shadows, glare from the sun.

BTW, both shadows and sun use PolygonOffset, which mentioned custom patch partially patches out.

**Comment by pulion** [comment] 2021-02-10 19:35
> Most of these error messages are caused by osg using GL_POLYGON_OFFSET_LINE/GL_POLYGON_OFFSET_POINT mode which isn't supported on gles. It shouldn't affect anything, regardless I've patched it out just so that it doesn't spam the log. you can try the new build and let me know if it works any better.

I tested the APK Docent27 based on your patch.  really spam like before is gone.  but at times the error still appears.
https://drive.google.com/file/d/1AzVO2NOr2jvy2Flt1KeJW3KoSv_v0Esd/view?usp=drivesdk

**Comment by xyzz** [comment] 2021-02-10 19:55
For the record you can also download an apk from latest github action eg https://github.com/xyzz/openmw-android/actions/runs/555477920

**Comment by docent27** [comment] 2021-02-10 20:07
Sorry, I didn't understand you.  Download the APK that I got based on your patch?  I don't know how to attach it here, except somewhere on the cloud.

**Comment by xyzz** [comment] 2021-02-24 01:40
Closing as the original issue is solved, if occasional errors in the log are still causing trouble please open another issue.

**Closed by xyzz** 2021-02-24 01:40 UTC
